### ISSUE TITLE
Jinja2/Python: No system command execution capabilities detected

### ISSUE THREAD

**Issue by kernc** [epinna/tplmap#46]
Have a vulnerable server using Jinja2 incorrectly. tplmap says that "no system command execution capabilities have been detected on the target."

But I can inject `{{ [].__class__.__bases__[-1].__subclasses__()[79] }}` to reach `<class 'subprocess.Popen'>`, and surely something can be done with that ...

**Comment by epinna** [comment]
Hello kernc,

Tplmap is not a magic wand that is able to exploit anything, and it just tries one (reasonably portable) rendered command execution payload for every supported engine. 

It may happen that the automated exploitation doesn't work, maybe due to some upstream filtering or some changes introduced in recent versions. I hope it is still useful to point the people to the injection points to be inspected manually.

I'll keep this isse open to check if your payload is more portable than the one currently included. Thanks for your contribution!

**Comment by kernc** [comment]
`object.__subclasses__()` lists all subclasses that are imported and extend object type. In case of Python3, if `subprocess.Popen` is available and can be passed a list of strings, that's that. In Python2, `<type 'file'>` is always available, which can open and read/write a file. Digging up through `object.__subclasses__()` sure is some portable approach.

https://www.google.com/search?q=template+injection+__subclasses__

**Comment by epinna** [comment]
Guys, this is super cool, thanks for it. 

I also realized we do not have a testing environment for Python3, I'm going to implement it and modify the payloads to be portable, if possible.

**Comment by epinna** [comment]
This should be fixed using @jx6f Python3 payload with some adjustment to be portable. All the template engines are now tested both against Python2 and 3.

**Comment by jx6f** [comment]
Awesome:tada:  Thank you so much!
